//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/EditorActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/EditorActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @EditorActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @EditorActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""EditorActions"",
    ""maps"": [
        {
            ""name"": ""UIEditor"",
            ""id"": ""ac5b86b6-6c07-4a72-9e65-f9201567a86e"",
            ""actions"": [
                {
                    ""name"": ""FormatBold"",
                    ""type"": ""Button"",
                    ""id"": ""f98c3122-66b5-49f8-9031-118cecd83f65"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FormatItalic"",
                    ""type"": ""Button"",
                    ""id"": ""dfad148d-5902-4001-93ef-9fa0bbc1dd95"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InsertTab"",
                    ""type"": ""Button"",
                    ""id"": ""15e4309b-aa78-40b6-b0b6-5b42158dd2a5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""8cd32117-b310-4b48-a8cc-8b0a97c4239b"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FormatBold"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""1b18f3ac-5353-4465-a7c5-866610f9e67b"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FormatBold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""1b872b06-7a1b-4c72-ab59-44fbd7df96d3"",
                    ""path"": ""<Keyboard>/leftAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FormatBold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""46e81265-55be-45fd-a852-dcece0137c61"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FormatItalic"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""f39ddcc0-66e7-47cf-8548-b622cd703533"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FormatItalic"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""ea59918c-eeea-43cf-8041-18a0cc3e716d"",
                    ""path"": ""<Keyboard>/leftAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FormatItalic"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""400da4b2-4ea5-4bc6-afdf-bc8d74cac877"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InsertTab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // UIEditor
        m_UIEditor = asset.FindActionMap("UIEditor", throwIfNotFound: true);
        m_UIEditor_FormatBold = m_UIEditor.FindAction("FormatBold", throwIfNotFound: true);
        m_UIEditor_FormatItalic = m_UIEditor.FindAction("FormatItalic", throwIfNotFound: true);
        m_UIEditor_InsertTab = m_UIEditor.FindAction("InsertTab", throwIfNotFound: true);
    }

    ~@EditorActions()
    {
        UnityEngine.Debug.Assert(!m_UIEditor.enabled, "This will cause a leak and performance issues, EditorActions.UIEditor.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UIEditor
    private readonly InputActionMap m_UIEditor;
    private List<IUIEditorActions> m_UIEditorActionsCallbackInterfaces = new List<IUIEditorActions>();
    private readonly InputAction m_UIEditor_FormatBold;
    private readonly InputAction m_UIEditor_FormatItalic;
    private readonly InputAction m_UIEditor_InsertTab;
    /// <summary>
    /// Provides access to input actions defined in input action map "UIEditor".
    /// </summary>
    public struct UIEditorActions
    {
        private @EditorActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public UIEditorActions(@EditorActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "UIEditor/FormatBold".
        /// </summary>
        public InputAction @FormatBold => m_Wrapper.m_UIEditor_FormatBold;
        /// <summary>
        /// Provides access to the underlying input action "UIEditor/FormatItalic".
        /// </summary>
        public InputAction @FormatItalic => m_Wrapper.m_UIEditor_FormatItalic;
        /// <summary>
        /// Provides access to the underlying input action "UIEditor/InsertTab".
        /// </summary>
        public InputAction @InsertTab => m_Wrapper.m_UIEditor_InsertTab;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_UIEditor; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="UIEditorActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(UIEditorActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="UIEditorActions" />
        public void AddCallbacks(IUIEditorActions instance)
        {
            if (instance == null || m_Wrapper.m_UIEditorActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIEditorActionsCallbackInterfaces.Add(instance);
            @FormatBold.started += instance.OnFormatBold;
            @FormatBold.performed += instance.OnFormatBold;
            @FormatBold.canceled += instance.OnFormatBold;
            @FormatItalic.started += instance.OnFormatItalic;
            @FormatItalic.performed += instance.OnFormatItalic;
            @FormatItalic.canceled += instance.OnFormatItalic;
            @InsertTab.started += instance.OnInsertTab;
            @InsertTab.performed += instance.OnInsertTab;
            @InsertTab.canceled += instance.OnInsertTab;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="UIEditorActions" />
        private void UnregisterCallbacks(IUIEditorActions instance)
        {
            @FormatBold.started -= instance.OnFormatBold;
            @FormatBold.performed -= instance.OnFormatBold;
            @FormatBold.canceled -= instance.OnFormatBold;
            @FormatItalic.started -= instance.OnFormatItalic;
            @FormatItalic.performed -= instance.OnFormatItalic;
            @FormatItalic.canceled -= instance.OnFormatItalic;
            @InsertTab.started -= instance.OnInsertTab;
            @InsertTab.performed -= instance.OnInsertTab;
            @InsertTab.canceled -= instance.OnInsertTab;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="UIEditorActions.UnregisterCallbacks(IUIEditorActions)" />.
        /// </summary>
        /// <seealso cref="UIEditorActions.UnregisterCallbacks(IUIEditorActions)" />
        public void RemoveCallbacks(IUIEditorActions instance)
        {
            if (m_Wrapper.m_UIEditorActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="UIEditorActions.AddCallbacks(IUIEditorActions)" />
        /// <seealso cref="UIEditorActions.RemoveCallbacks(IUIEditorActions)" />
        /// <seealso cref="UIEditorActions.UnregisterCallbacks(IUIEditorActions)" />
        public void SetCallbacks(IUIEditorActions instance)
        {
            foreach (var item in m_Wrapper.m_UIEditorActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIEditorActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="UIEditorActions" /> instance referencing this action map.
    /// </summary>
    public UIEditorActions @UIEditor => new UIEditorActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "UIEditor" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="UIEditorActions.AddCallbacks(IUIEditorActions)" />
    /// <seealso cref="UIEditorActions.RemoveCallbacks(IUIEditorActions)" />
    public interface IUIEditorActions
    {
        /// <summary>
        /// Method invoked when associated input action "FormatBold" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFormatBold(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "FormatItalic" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFormatItalic(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "InsertTab" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnInsertTab(InputAction.CallbackContext context);
    }
}
